from django.urls import path
from .views import (
    LoginView, AdminStatsView, CompanyListView, CompanyDetailView, AdminCompanyCreateView,
    SubscriptionPlanListView, TransactionListView, 
    UserManagementView, UserDetailView, SuperAdminListView,
    SupportQueryView, SupportQueryDetailView, ManagerEmployeeListView,
    HolidayView, AppreciationView, LeaveRequestView, LeaveRequestDetailView,
    CompanyPolicyView, CompanyPolicyDetailView, PayrollView,
    OffboardingView, OffboardingDetailView,
    LetterHeadView, LetterHeadDetailView, UserProfileView, AdminSettingsView,
    EmployeeStatsView, CalendarDataView, AssetView,
    ManagerAttendanceView, ManagerPerformanceView, ManagerNotificationView,
    EmployeeAttendanceView, EmployeeNotificationView,
    EmployeeClockInView, EmployeeClockOutView, EmployeeLeaveApplyView, EmployeeExpenseView, EmployeeAttendanceTodayView,
    ManagerLeaveApprovalView, ManagerTaskCreateView, ManagerTaskListView,
    EmployeeTaskListView, EmployeeTaskUpdateView, TaskDetailView,
    DocumentUploadView, EmployeeDocumentsView,
    ManagerProfileView, ManagerProfileUpdateView,
    EmployeeProfileView, EmployeeProfileUpdateView,
    OrgChartView, OrgChartDetailView, NotificationView, AllEmployeeProfilesView,
    TeamLeaderProfileView, TeamLeaderProfileUpdateView, TeamLeaderStatsView,
    TeamLeaderTeamMembersView, TeamLeaderAttendanceView, TeamLeaderTasksView, TeamLeaderPerformanceView,
    EmployeeExpenseListView, TeamLeaderExpenseListView, TeamLeaderExpenseUpdateView,
    ManagerExpenseListView, ManagerExpenseApproveView, ManagerExpensePayView
)

urlpatterns = [
    path('api/tasks/<int:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('api/notifications/', NotificationView.as_view(), name='notifications'),
    path('api/auth/login/', LoginView.as_view(), name='login'),
    path('api/manager/profile/', ManagerProfileView.as_view(), name='manager_profile'),
    path('api/manager/profile/update/', ManagerProfileUpdateView.as_view(), name='manager_profile_update'),
    path('api/user/profile/', UserProfileView.as_view(), name='user_profile'),
    path('api/admin/stats/', AdminStatsView.as_view(), name='admin_stats'),
    path('api/admin/companies/', CompanyListView.as_view(), name='companies'),
    path('api/admin/companies/<int:pk>/', CompanyDetailView.as_view(), name='company_detail'),
    path('api/admin/companies/create/', AdminCompanyCreateView.as_view(), name='admin_company_create'),
    path('api/admin/subscriptions/', SubscriptionPlanListView.as_view(), name='subscriptions'),
    path('api/admin/transactions/', TransactionListView.as_view(), name='transactions'),
    path('api/admin/users/', UserManagementView.as_view(), name='user_management'),
    path('api/admin/users/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('api/admin/superadmins/', SuperAdminListView.as_view(), name='superadmins'),
    path('api/admin/queries/', SupportQueryView.as_view(), name='support_queries'),
    path('api/admin/queries/<int:pk>/', SupportQueryDetailView.as_view(), name='support_query_detail'),
    path('api/admin/settings/', AdminSettingsView.as_view(), name='admin_settings'),
    path('api/manager/employees/', ManagerEmployeeListView.as_view(), name='manager_employees'),
    path('api/manager/holidays/', HolidayView.as_view(), name='holidays'),
    path('api/manager/appreciations/', AppreciationView.as_view(), name='appreciations'),
    path('api/manager/leaves/', LeaveRequestView.as_view(), name='manager_leaves'),
    path('api/manager/settings/', UserProfileView.as_view(), name='manager_settings'),
    path('api/manager/offboardings/', OffboardingView.as_view(), name='offboardings'),
    path('api/manager/offboardings/<int:pk>/', OffboardingDetailView.as_view(), name='offboarding_detail'),
    path('api/manager/letterheads/', LetterHeadView.as_view(), name='letterheads'),
    path('api/manager/letterheads/<int:pk>/', LetterHeadDetailView.as_view(), name='letterhead_detail'),
    path('api/manager/policies/<int:pk>/', CompanyPolicyDetailView.as_view(), name='manager_policy_detail'),
    path('api/manager/payroll/', PayrollView.as_view(), name='payroll'),
    path('api/manager/leaves/<int:pk>/', LeaveRequestDetailView.as_view(), name='manager_leave_detail'),
    path('api/manager/policies/', CompanyPolicyView.as_view(), name='manager_policies'),
    path('api/assets/',AssetView.as_view(),name='assets'),
    path('api/employee/stats/', EmployeeStatsView.as_view(), name='employee_stats'),
    path('api/assets/',AssetView.as_view(),name='assets'),
    path('api/employee/holidays/', HolidayView.as_view(), name='employee_holidays'),
    path('api/employee/appreciations/', AppreciationView.as_view(), name='employee_appreciations'),
    path('api/employee/leaves/', EmployeeLeaveApplyView.as_view(), name='employee_leaves'),
    path('api/employee/leaves/<int:pk>/', LeaveRequestDetailView.as_view(), name='employee_leave_detail'),
    path('api/employee/policies/', CompanyPolicyView.as_view(), name='employee_policies'),
    path('api/employee/payroll/', PayrollView.as_view(), name='employee_payroll'),
    path('api/employee/settings/', UserProfileView.as_view(), name='employee_settings'),
    path('api/employee/offboardings/', OffboardingView.as_view(), name='employee_offboardings'),
    path('api/employee/profile/', EmployeeProfileView.as_view(), name='employee_profile'),
    path('api/employee/profile/update/', EmployeeProfileUpdateView.as_view(), name='employee_profile_update'),
    path('api/manager/attendance/', ManagerAttendanceView.as_view(), name='manager_attendance'),
    path('api/manager/performance/', ManagerPerformanceView.as_view(), name='manager_performance'),
    path('api/manager/notifications/', ManagerNotificationView.as_view(), name='manager_notifications'),
    path('api/policies/', CompanyPolicyView.as_view(), name='policies_list'),
    path('api/policies/create/', CompanyPolicyView.as_view(), name='policy_create'),
    path('api/policies/update/<int:pk>/', CompanyPolicyDetailView.as_view(), name='policy_update'),
    path('api/policies/delete/<int:pk>/', CompanyPolicyDetailView.as_view(), name='policy_delete'),
    path('api/documents/upload/', DocumentUploadView.as_view(), name='document_upload'),
    path('api/employee/documents/', EmployeeDocumentsView.as_view(), name='employee_documents'),
    path('api/employee/attendance/', EmployeeAttendanceView.as_view(), name='employee_attendance'),
    path('api/employee/notifications/', EmployeeNotificationView.as_view(), name='employee_notifications'),
    path('api/calendar-data/', CalendarDataView.as_view(), name='calendar_data'),
    path('api/employee/attendance/clock-in/', EmployeeClockInView.as_view(), name='employee_clock_in'),
    path('api/employee/attendance/clock-out/', EmployeeClockOutView.as_view(), name='employee_clock_out'),
    path('api/employee/attendance/today/', EmployeeAttendanceTodayView.as_view(), name='employee_attendance_today'),
    path('api/employee/leaves/apply/', EmployeeLeaveApplyView.as_view(), name='employee_leave_apply'),
    path('api/employee/expenses/', EmployeeExpenseListView.as_view(), name='employee_expenses_list'),
    path('api/employee/expenses/create/', EmployeeExpenseListView.as_view(), name='employee_expense_create'),
    path('api/teamleader/expenses/', TeamLeaderExpenseListView.as_view(), name='tl_expenses_list'),
    path('api/teamleader/expenses/update/', TeamLeaderExpenseUpdateView.as_view(), name='tl_expense_update'),
    path('api/manager/expenses/', ManagerExpenseListView.as_view(), name='manager_expenses_list'),
    path('api/manager/expenses/approve/', ManagerExpenseApproveView.as_view(), name='manager_expense_approve'),
    path('api/manager/expenses/pay/', ManagerExpensePayView.as_view(), name='manager_expense_pay'),
    path('api/manager/leaves/update-status/', ManagerLeaveApprovalView.as_view(), name='manager_leave_approval'),
    path('api/manager/tasks/create/', ManagerTaskCreateView.as_view(), name='manager_task_create'),
    path('api/manager/tasks/', ManagerTaskListView.as_view(), name='manager_tasks'),
    path('api/employee/tasks/', EmployeeTaskListView.as_view(), name='employee_tasks'),
    path('api/employee/tasks/update/', EmployeeTaskUpdateView.as_view(), name='employee_task_update'),
    path('api/org-chart/', OrgChartView.as_view(), name='org_chart'),
    path('api/org-chart/<int:pk>/', OrgChartDetailView.as_view(), name='org_chart_detail'),
    path('api/manager/all-employee-profiles/', AllEmployeeProfilesView.as_view(), name='all_employee_profiles'),
    path('api/teamleader/profile/', TeamLeaderProfileView.as_view(), name='tl_profile'),
    path('api/teamleader/profile/update/', TeamLeaderProfileUpdateView.as_view(), name='tl_profile_update'),
    path('api/teamleader/stats/', TeamLeaderStatsView.as_view(), name='tl_stats'),
    path('api/teamleader/team-members/', TeamLeaderTeamMembersView.as_view(), name='tl_members'),
    path('api/teamleader/attendance/', TeamLeaderAttendanceView.as_view(), name='tl_attendance'),
    path('api/teamleader/tasks/', TeamLeaderTasksView.as_view(), name='tl_tasks'),
    path('api/teamleader/performance/', TeamLeaderPerformanceView.as_view(), name='tl_performance'),
]