# Generated by Django 5.2.13 on 2026-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_company_members_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('duration_months', models.IntegerField(default=1)),
                ('features', models.TextField(blank=True)),
                ('trial_period_days', models.IntegerField(default=7)),
            ],
        ),
    ]
