# Generated by Django 5.2.13 on 2026-04-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_companypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
    ]
