# Generated by Django 5.2.13 on 2026-04-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='casual_leaves',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leaves',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation_leaves',
            field=models.IntegerField(default=6),
        ),
    ]
