# Generated by Django 5.2.13 on 2026-04-28 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_employee_casual_leaves_employee_sick_leaves_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'Warning'), ('termination', 'Termination'), ('resignation', 'Resignation'), ('complaint', 'Complaint')], max_length=20)),
                ('reason', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboardings', to='myapp.employee')),
            ],
        ),
    ]
