# Generated by Django 5.2.13 on 2026-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_offboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('internship_offer', 'Internship Offer Letter'), ('self_declaration', 'Self Declaration Form'), ('payslip', 'Payslip'), ('employment_bond', 'Employment Bond')], max_length=50)),
                ('file', models.FileField(upload_to='letterheads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
