# Generated by Django 5.2.13 on 2026-04-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='profile_picture',
        ),
    ]
