# Generated by Django 6.0.4 on 2026-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_employee_account_number_employee_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='CompanyDocument',
        ),
    ]
