# Generated by Django 6.0.4 on 2026-05-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_company_status_company_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='orgchart')),
                ('department', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('employee_months', models.IntegerField()),
                ('work_mode', models.CharField(choices=[('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='remote', max_length=50)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='myapp.orgchart')),
            ],
        ),
    ]
