# Generated by Django 6.0.4 on 2026-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='employee_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
